### ISSUE TITLE
excuse me, how long will sf-eosio and sf-ethereum be open?

### ISSUE THREAD

**Issue by cppfuns** [dfuse-io/manageos#13]
https://github.com/streamingfast/sf-eosio
https://github.com/streamingfast/sf-ethereum

**Comment by maoueh** [comment]
It will really soon. https://github.com/streamingfast/sf-eosio is actually https://github.com/dfuse-io/dfuse-eosio that will move.

The other one will be open this week. Did you had problems?

**Comment by maoueh** [comment]
https://github.com/streamingfast/sf-ethereum is now open source, the move to `sf-eosio` should happen this week.
