### ISSUE TITLE
new merging mechanism cause some incomplete or skipped bundles

### ISSUE THREAD

**Issue by sduchesneau** [dfuse-io/manageos#19]
We want the system to behave in the best possible way for each condition:

# [scenario 1] 
## conditions:
* node sends first block 123
* merging is enabled (either because --merge-directly is used or because block 123 is older than the age threshold)

## expected behavior:
* blocks 123 to 199 will be sent as one-block-files (because we don't have a complete bundle starting at 100...)
* merged blocks 200-299, 300-399, etc. will be produced

# [scenario 2] -- when we select a start-block for reprocessing --
## conditions:
* same conditions as [scenario 1], PLUS:
* --start-block=200
## expected behavior:
* blocks 123 to 199 will be skipped (discarded) because of the start-block
* merged blocks 200-299, 300-399, etc. will be produced

# [scenario 3] -- interrupted scenario 2, then started again --
## conditions:
* node sends first block 450
* blocks 400 to 449 already exist on the local store "mergeable"
* merging is enabled (either because --merge-directly is used or because block 450 is older than the age threshold)
* --start-block=200
## expected behavior:
* upon seeing the first block being 450, the 'start-block' flag will be effectively ignored
* the system will read blocks 400 to 449 from disk and validate that they can be "linked" to the first block received (450)
* merged blocks 400-499, etc. will be produced

# [scenario 4] -- interrupted scenario 1, then started again --
## conditions:
* node sends first block 450
* merging is enabled (either because --merge-directly is used or because block 450 is older than the age threshold)
* blocks 400 to 449 exist on the local store "mergeable"
## expected behavior:
* the system will read blocks 400 to 449 from disk and validate that they can be "linked" to the first block received (450)
* merged blocks 400-500, etc. will be produced

# [scenario 5] -- interrupted scenario 1, then started again but the node skipped a block (a hole will be produced)--
## conditions:
* node sends first block 451
* merging is enabled (either because --merge-directly is used or because block 450 is older than the age threshold)
* blocks 400 to 449 exist on the local store "mergeable"
# expected behavior:
* the system will stop processing as soon as it gets block 451. any block that it reads before the node can shutdown will be sent as one-blocks, but the fast shutdown will indicate to the operator that something is wrong and that the files in the folder 'uploadable' should be deleted before the reprocessing is restarted.

**Comment by sduchesneau** [comment]
Under some conditions, the node-manager will silently produce incomplete merged blocks, I'm reviewing the logic here

**Comment by matthewdarwin** [comment]
The original issue was things like:
```
(mindreader) failed storing block in archiver, shutting down. You will need to reprocess over this range to get this block {"error": "loading partial: walking
 mergeable one block files: unable to read one block "0006445300-20220226T201323.0-1c2068f4-803cb395-6445100-dom37": unable to read file header: EOF", "block": "#6445347 (cdfacebea23a6382557a3ac996393134f99e01140db8fa22d0dd6c4
5692e2d17)"}
```

**Comment by sduchesneau** [comment]
Fixed in [commit](https://github.com/streamingfast/node-manager/commit/52cfbe72a0ea64c6437dd8ba4d66579b107b244b)
