### ISSUE TITLE
Enhancement: only upload blocks if merger needs them

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/manageos#21]
If I set mindreader-node-merge-threshold-block-age, then mindreader will sometimes merge blocks and sometimes not. The location to upload files to is either: common-oneblock-store-url or common-blocks-store-url.

It would be more efficient to skip merging and uploading entirely if the merger doesn't need them.

Currently mindreader can sync with blockmeta to understand where the chain is at, but it doesn't understand where the merger is at.  If there was a way mindreader could understand merger's status then it could avoid sending blocks that are not required.

**Comment by sduchesneau** [comment]
The blockmeta (with its database, etc.) is not part of the "modern, lean" version of firehose, so we don't want to depend on it or build more features around it at the time.

The merger is able to easily skip/delete blocks that are too old, or to ignore blocks that are way ahead.
I'm not sure what you are trying to "save" by skipping the upload of merged files...

**Comment by matthewdarwin** [comment]
I'm only trying to save processing load.  If you have an infrastructure that is just booting up (after a crash or whatever), then things are very overloaded as things get in sync. The more 'unecessary' processing load that can be removed, the better (speaking from an operations point of view). 

This is low priority.

**Comment by matthewdarwin** [comment]
Just to be clear, we didn't deploy blockmeta service for SF (only there for older dfuse), so not asking for it to come back. ;-)

**Comment by maoueh** [comment]
Closing, every thing is found under https://github.com/streamingfast/firehose-core now anyway. Going to make this repo read-only.
