### ISSUE TITLE
Fatal out if mindreader-node-merge-threshold-block-age < 60s

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/manageos#23]
You can set very small values of `mindreader-node-merge-threshold-block-age`.  When this happens it is probably a configuration mistake.  Like if less than a few minutes.

**Comment by maoueh** [comment]
The actual value would need to be chain specific most probably.

In fact @sduchesneau, is now even possible to let Mindreader run forevers in auto-merge mode?

**Comment by matthewdarwin** [comment]
My goal is only to prevent typos.  "900" instead of "900s" in this case.

With all the recent changes, I would assume it would be fine to run forever in auto-merge mode if you only have one mindreader.

**Comment by sduchesneau** [comment]
I do not believe it will support running in auto-merge mode close to head. You *should* run a merger process, even if the merger process only processes the blocks of a single mindreader.

A sane one-mindreader deployment would be:
* a decent threshold-block-age (ex: 1h on eth-mainnet, 10 minutes on EOS mainnet, etc.)
* a merger running in another process

I can implement: if value is less than 10 seconds, bail out (if you want to merge EVERYTHING' use the other flag, merge-and-store-directly)

**Comment by sduchesneau** [comment]
fixed: To github.com:streamingfast/sf-ethereum
   75649ed..a0e3e44  develop -> develop
