### ISSUE TITLE
mindreader should not try to connect to non-existent blockmeta

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/manageos#25]
I have `mindreader-node-merge-threshold-block-age: 3h`

While BSC is catching up, I see lots of messages like this in the log:

```
(mindreader) failed getting last lib from blockmeta {"error": "tracker getter for target \"network-lib\": no getter defined"}
```

every 30 seconds.

Blockmeta no longer exists, it should not be used.

**Comment by Qjawko** [comment]
Hi, have you solved it? Same issue

**Comment by matthewdarwin** [comment]
I think this is solved already.
