### ISSUE TITLE
mindreader should publish metric to prometheus about last block successfully uploaded to s3

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/manageos#27]
mindreader should publish metric to prometheus about last block successfully uploaded to s3

Mindreader head_block_drift shows if it is keeping up with blocks on chain, but not if those blocks were sent up to the merger (s3 or whatever storage).  Would be helpful to know the "upload drift".  ie, are blocks piling up on mindreader.

Related to: https://github.com/streamingfast/node-manager/issues/26

**Comment by matthewdarwin** [comment]
currently we have a monitor that counts number of files in mindreader "work" directory to simulate this.

**Comment by maoueh** [comment]
Closing, every thing is found under https://github.com/streamingfast/firehose-core now anyway. Going to make this repo read-only.
