### ISSUE TITLE
mindreader auto-merge broken using release/v0.10.x 

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/manageos#29]
I started from a geth backup from a few weeks back.  mindreader won't merge anything.
All the files pile up in mindreader/work/mergeable.
Stopping, removing all the files in `mindreader/work/mergeable` and restarting results in the same thing.

Full debug logs available upon request.

**Comment by matthewdarwin** [comment]
2022-04-30T15:09:36.742Z DEBG (bstream) found root or hole. did not reach requested block {"requested_block_num": 6530600, "missing_id": "9321a4f8"}

**Comment by maoueh** [comment]
Closing, every thing is found under https://github.com/streamingfast/firehose-core now anyway. Going to make this repo read-only.
