### ISSUE TITLE
mindreader: copy bootstrap-data-url to node-data-dir on every sfeth startup

### ISSUE THREAD

**Issue by sajjadbaeidi** [dfuse-io/manageos#30]
If `mindreader-node-bootstrap-data-url` is set, it gets copied to  `mindreader-node-data-dir`. This is good.  but if  the **genesis.json** changes, on the next **sfeth** startup the genesis.json should be re-copied again to `mindreader-node-data-dir`

**Comment by maoueh** [comment]
This is not supported anymore.
