### ISSUE TITLE
 Rewrite node operations to use bash scripts to start, stop and backup the node

### ISSUE THREAD

**Issue by sduchesneau** [dfuse-io/manageos#36]
Remove the heavy logic (in this repo and injected from firehose-*** repos) for snapshots, node operation, etc.
bash scripts should be provided by the user (copied from examples with sane values).

* `start` : starts the node and outputs the logs to STDOUT and STDERR as usual
* `stop`: stops the node
* `backup`: runs the backup, it can call `curl localhost:8080/v1/stop|start` if needed
* `restore`: runs the backup, it can call `curl localhost:8080/v1/stop|start` if needed
* `heartbeat`: this script is run in a loop, sleeps 1sec between runs.
(optional, new feature request: * `onfailure`: this script is run when the node suddenly stops. It can decide to call 'restore' or 'shutdown' or just 'start' or whatever logic)

the node manager API listens on 8080:
* start, stop, shutdown, backup, restore

strong suggestion: We get rid of the "node" type of service, only `reader` remains

**Comment by maoueh** [comment]
Every being standard "execution, it's easy to use `bash` script to control "node" software:

```
reader-node-binary: bash
reader-node-arguments:
- -c
- ...
```

There is a also `reader-node-bootstrap-data-url` that accepts `bash://<absolute-path-to-script>` so just bootstrapping from `bash` is also possible.
